---
- name: "{{ mysqld_task_prefix }} Load dependencies"
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      paths:
        - 'vars'

- name: "{{ mysqld_task_prefix }} Install dependencies"
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ mysqld_dependecies }}"
  when: ansible_distribution == "Debian"
...
